<?php
/**
 * ElectronicInvoiceStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Popsicle\Amazon
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Popsicle\Amazon\Model\Orders;
use \Popsicle\Amazon\ObjectSerializer;

/**
 * ElectronicInvoiceStatus Class Doc Comment
 *
 * @category Class
 * @description The status of the electronic invoice.
 * @package  Popsicle\Amazon
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ElectronicInvoiceStatus
{
    /**
     * Possible values of this enum
     */
    const NOT_REQUIRED = 'NotRequired';
const NOT_FOUND = 'NotFound';
const PROCESSING = 'Processing';
const ERRORED = 'Errored';
const ACCEPTED = 'Accepted';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOT_REQUIRED,
self::NOT_FOUND,
self::PROCESSING,
self::ERRORED,
self::ACCEPTED,        ];
    }
}
