<?php
/**
 * OrderItemStatusAcknowledgementStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Popsicle\Amazon
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Retail Procurement Orders
 *
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Popsicle\Amazon;

/**
 * OrderItemStatusAcknowledgementStatusTest Class Doc Comment
 *
 * @category    Class
 * @description Acknowledgement status information.
 * @package     Popsicle\Amazon
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderItemStatusAcknowledgementStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderItemStatusAcknowledgementStatus"
     */
    public function testOrderItemStatusAcknowledgementStatus()
    {
    }

    /**
     * Test attribute "confirmation_status"
     */
    public function testPropertyConfirmationStatus()
    {
    }

    /**
     * Test attribute "accepted_quantity"
     */
    public function testPropertyAcceptedQuantity()
    {
    }

    /**
     * Test attribute "rejected_quantity"
     */
    public function testPropertyRejectedQuantity()
    {
    }

    /**
     * Test attribute "acknowledgement_status_details"
     */
    public function testPropertyAcknowledgementStatusDetails()
    {
    }
}
