<?php
/**
 * StandardSingleImageSpecsDetailModuleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Popsicle\Amazon
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Popsicle\Amazon;

/**
 * StandardSingleImageSpecsDetailModuleTest Class Doc Comment
 *
 * @category    Class
 * @description A standard image with paragraphs and a bulleted list, and extra space for technical details.
 * @package     Popsicle\Amazon
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StandardSingleImageSpecsDetailModuleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StandardSingleImageSpecsDetailModule"
     */
    public function testStandardSingleImageSpecsDetailModule()
    {
    }

    /**
     * Test attribute "headline"
     */
    public function testPropertyHeadline()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "description_headline"
     */
    public function testPropertyDescriptionHeadline()
    {
    }

    /**
     * Test attribute "description_block1"
     */
    public function testPropertyDescriptionBlock1()
    {
    }

    /**
     * Test attribute "description_block2"
     */
    public function testPropertyDescriptionBlock2()
    {
    }

    /**
     * Test attribute "specification_headline"
     */
    public function testPropertySpecificationHeadline()
    {
    }

    /**
     * Test attribute "specification_list_block"
     */
    public function testPropertySpecificationListBlock()
    {
    }

    /**
     * Test attribute "specification_text_block"
     */
    public function testPropertySpecificationTextBlock()
    {
    }
}
