<?php
/**
 * VendorShippingLabelsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Popsicle\Amazon
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Popsicle\Amazon;

use Popsicle\Amazon\Configuration;
use Popsicle\Amazon\ApiException;
use Popsicle\Amazon\ObjectSerializer;

/**
 * VendorShippingLabelsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Popsicle\Amazon
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VendorShippingLabelsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getShippingLabel
     *
     * .
     *
     */
    public function testGetShippingLabel()
    {
    }

    /**
     * Test case for getShippingLabels
     *
     * .
     *
     */
    public function testGetShippingLabels()
    {
    }

    /**
     * Test case for submitShippingLabelRequest
     *
     * .
     *
     */
    public function testSubmitShippingLabelRequest()
    {
    }
}
